### ISSUE TITLE
Color() class conflict throught project

### ISSUE THREAD

**Issue by HarrySingh30** [spiky-star/FlareLine-CRM#1]
There is same class exists in 'dart:ui' package as well as in 'faker/faker.dart' package named **Color()**

**Suggestion** :-  Should import faker package something like this   "import 'package:faker/faker.dart' as fake;" and should use faker package like this "faker = fake.Faker()". 

**Note**:-  I am unaware of github community guidelines yet so accept applogies if did not follow any guideline in this suggestion.

**Comment by spiky-star** [comment]
good idea, I'will check
